[package]
name = "bilge"
version = "0.1.0"
authors = ["JackThomson2 <jackathomson@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
atomic-counter = "1"
rand = "*"
typenum = "1.4"
dashmap = "4.0.0-rc6"
colored = { git = "https://github.com/tforgione/colored" }
mimalloc = { version = "*", default-features = false }
rayon = { version = "1.5.0" }
ahash = { version = "0.5.7", features = ["specialize"], default-features= false }
arrayvec = { version = "0.5.2", features = ["unstable-const-fn", "array-sizes-33-128"] }
wyhash = "0.4.2"

[profile.release]
panic = "abort"
opt-level = 3
codegen-units = 1
lto = "fat"

[[bin]]
name = "bilgebot"
path = "src/main.rs"
