[package]
name = "bilge"
version = "0.1.0"
authors = ["JackThomson2 <jackathomson@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic-counter = "1"
aes = "0.3"
rand = "*"
hashbrown = "0.7"
bit-array = "0.4"
typenum = "1.4"
num_cpus = "1.1"
dashmap = "4.0.0-rc3"
colored = { git = "https://github.com/tforgione/colored" }
uvth = "*"
mimalloc = { version = "*", default-features = false }
arrayvec = "0.5"
seahash = "4"
wmi = "0.4"
serde = "*"
rayon = { git = "https://github.com/nikomatsakis/rayon", branch = "latch-target-thread-2" }
base64 = "0.12.1"

[profile.release]
panic = "abort"
opt-level = 3
codegen-units = 1
lto = "fat"

[[bin]]
name = "bilgebot"
path = "src/main.rs"
