[package]
name = "bilge"
version = "0.1.0"
authors = ["JackThomson2 <jackathomson@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
dashmap = "3.4"
num_cpus = "1.1"
colored = {git = "https://github.com/tforgione/colored"}
scrap = "0.5.0"
lodepng = "2.0.0"
mimalloc = { version = "*", default-features = false }

[profile.release]
codegen-units = 1
lto = true