[package]
name = "bilge"
version = "0.1.0"
authors = ["JackThomson2 <jackathomson@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atomic-counter = "1"
rand = "*"
hashbrown = "0.7"
bit-array = "0.4"
typenum = "1.4"
num_cpus = "1.1"
dashmap = "3"
colored = { git = "https://github.com/tforgione/colored" }
scrap = "0.5.0"
lodepng = "2.0.0"
uvth = "*"
aho-corasick = "0.7"
snmalloc-rs = "0.2"
arrayvec = "0.5"
seahash = "4"
rayon = { git = "https://github.com/nikomatsakis/rayon", branch = "latch-target-thread-2" }

[profile.release]
panic = "abort"
opt-level = 3
codegen-units = 1
lto = "fat"
debug = true

[[bin]]
name = "bilgebot"
path = "src/main.rs"
