[package]
name = "bilge"
version = "0.1.0"
authors = ["JackThomson2 <jackathomson@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
atomic-counter = "1"
rand = "*"
bit-array = "0.4"
typenum = "1.4"
dashmap = "4.0.0-rc4"
colored = { git = "https://github.com/tforgione/colored" }
mimalloc = { version = "*", default-features = false }
serde = "*"
rayon = { version = "1.5.0" }
base64 = "0.12.1"
smallvec = { version = "1.5.0", features = ["union", "const_generics"] }
ahash = { version = "0.5.8", features = ["specialize"] }
arrayvec = { version = "0.5.2", features = ["unstable-const-fn", "array-sizes-33-128"] }

[profile.release]
panic = "abort"
opt-level = 3
codegen-units = 1
lto = "fat"

[[bin]]
name = "bilgebot"
path = "src/main.rs"
